services:
  mysql:
    image: mysql:8.0
    container_name: vet_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: vet_db
      MYSQL_USER: vet
      MYSQL_PASSWORD: vet
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - vet_network

  springboot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vet_backend
    entrypoint: ["/bin/sh", "-c", "sleep 15 && java -jar app.jar"]
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://vet_mysql:3306/vet_db
      SPRING_DATASOURCE_USERNAME: vet
      SPRING_DATASOURCE_PASSWORD: vet
    ports:
      - "8080:8080"
    networks:
      - vet_network

volumes:
  mysql_data:

networks:
  vet_network:
