services:
  mysql:
    image: mysql:8.0
    container_name: vet_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: vet_db
      MYSQL_USER: vet
      MYSQL_PASSWORD: vet
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - vet_network

volumes:
  mysql_data:

networks:
  vet_network:
